### ISSUE TITLE
gulp appx:dev fails

### ISSUE THREAD

**Issue by luisrudge** [MicrosoftEdge/generator-appx#2]
Instead of opening an app, it opens a browser.

I'm running win10 10162

![image](https://cloud.githubusercontent.com/assets/941075/8489618/dc1e5e42-20f3-11e5-91a1-e17dd369f99f.png)

**Comment by alxlu** [comment]
Hi @luisrudge, do you have [Developer Mode](https://msdn.microsoft.com/en-us/library/windows/apps/dn706236.aspx) enabled?
![ic795457](https://cloud.githubusercontent.com/assets/3271834/8502120/04b1b620-2161-11e5-965d-adde883ee821.png).

**Comment by luisrudge** [comment]
wow! I didn't know that existed. Is that documented anywhere? If it is, I'm sorry. Thanks for the help, man!
One question: Can I use windows 10 apis with this app?

**Comment by alxlu** [comment]
Hmm.. it looks like it isn't documented in the wiki. I'll go add it in.

And yes! You can use most of the WinRT APIs. There are a few examples you can check out [here](http://rjs.azurewebsites.net/).

Please feel free to reach out if you have any additional questions!

**Comment by luisrudge** [comment]
Awesome. Thanks!

**Comment by Gr8Gatsby** [comment]
luisrudge if you want to see some examples I've started posting some Gists: 
- [Customize App Title Bar colors](https://gist.github.com/Gr8Gatsby/5fe8f40593f545b1c70e)
- [Update LiveTile Image](https://gist.github.com/Gr8Gatsby/64428ebe2a82c47880d0) 
- [Customize Toast messages and receive userInput](https://gist.github.com/Gr8Gatsby/11d8c5a54507d52f41dc)
  *[More...](https://gist.github.com/Gr8Gatsby)

The important thing is to feature detect for the Windows namespace.  While in general you can just do something like this:

``` javascript
if ( typeof Windows !== 'undefined') 
```

to be more robust you can have a pattern more like this:

``` javascript
if (typeof Windows !== 'undefined' &&
        typeof Windows.UI !== 'undefined' &&
        typeof Windows.UI.ViewManagement !== 'undefined') {
    // Your code here code
}
```

If there are any examples you'd like to see please let us know.

**Comment by luisrudge** [comment]
Is there any case where `Windows` exists but Windows.UI doesn't?

**Comment by Gr8Gatsby** [comment]
You are able to define your own surface area to expose, but this is not the common case.
